# Generated by Django 4.2.5 on 2024-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.PositiveSmallIntegerField(verbose_name='ID теста')),
                ('session_id', models.PositiveSmallIntegerField(verbose_name='ID сессии')),
                ('question_id', models.PositiveSmallIntegerField(verbose_name='ID вопроса')),
                ('text_answer', models.CharField(max_length=50, null=True, verbose_name='Текстовый ответ на вопрос')),
                ('image_answer', models.ImageField(null=True, upload_to='image_answer/', verbose_name='Графический ответ на вопрос')),
                ('ranking', models.PositiveSmallIntegerField(null=True, verbose_name='Оценка ответа в баллах')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
