# Generated by Django 4.2.5 on 2024-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_self', '0002_alter_answer_image_answer_alter_answer_ranking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время открытия сесси')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_pair_session_question',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('session_id', 'question_id'), name='unique_pair_session-question'),
        ),
    ]
