name: workflow

on:
  push:
    branches: [ "some_branch" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install & configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Poetry init
        run: poetry init
      - name: Install flake8
        run: poetry add flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
      - name: Run flake8
        run: poetry run python -m flake8

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Bot to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./bot
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bot-backend:latest
      - name: Push Expert System to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./expert-system
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expert-system-backend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bot-backend
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/expert-system-backend
            docker compose stop
            docker compose rm web
            rm .env
            touch .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.POSTGRES_HOST }} >> .env
            echo DB_PORT=${{ secrets.POSTGRES_PORT }} >> .env
            echo DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} >> .env
            echo DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }} >> .env
            echo DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }} >> .env
            echo WEBHOOK_MODE=${{ secrets.WEBHOOK_MODE }} >> .env
            echo telegram_api_token=${{ secrets.telegram_api_token }} >> .env
            docker compose up -d --build
            sudo docker restart nginx-1
            sudo docker image prune --force
