name: test workflow

on:
  push:
    branches: [ "feature/deploy" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install & configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install -C bot --no-interaction --no-root
      - name: Add test
        run: poetry add -C bot flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
      - name: Run flake8
        run: poetry run -C bot python -m flake8
